# Generated by Django 2.2.2 on 2019-06-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_final_migrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
