# Generated by Django 2.2.2 on 2019-06-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20190620_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'get_latest_by': 'published', 'ordering': ['-published'], 'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to=None,
        ),
    ]
