# Generated by Django 2.2.2 on 2019-06-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_advuser_machine_spare'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together={('title', 'published')},
        ),
    ]
