# Generated by Django 2.2.2 on 2019-06-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20190618_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'get_latest_by': 'published', 'ordering': ['-published'], 'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
    ]
